# Generated by Django 3.2.8 on 2022-05-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, unique=True)),
                ('password', models.CharField(blank=True, max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=255, unique=True)),
                ('wants', models.CharField(blank=True, max_length=255, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('avatar', models.ImageField(default='avatars/default.jpg', upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
