# Generated by Django 3.2.8 on 2022-06-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_account_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='age',
        ),
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='account',
            name='wants',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
