# Generated by Django 3.2.8 on 2022-06-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220615_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
