# Generated by Django 3.2.8 on 2022-06-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
