# Generated by Django 3.2.8 on 2022-06-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220622_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='services',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
