# Generated by Django 3.2.8 on 2022-05-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like',
        ),
    ]
