# Generated by Django 3.2.8 on 2022-05-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_remove_likes_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='used_liked',
            new_name='user_liked',
        ),
    ]
